CREATE TABLE MEMBER (
NAME	VARCHAR2(30),
ID	VARCHAR2(30),
PASS	VARCHAR2(30),
BIRTH	NUMBER(4,0),
GENDER	VARCHAR2(30),
JOB	VARCHAR2(30),
ADDRESS	VARCHAR2(600),
REGDATE		DATE,
CONSTRAINT MEMBER_PK PRIMARY KEY (ID)
)

INSERT INTO MEMBER VALUES('홍길동', 'HONG', '1234', 1989, '남자', '학생', '서울시 종로구', SYSDATE);


CREATE TABLE MEMBER (
NAME	VARCHAR(30),
ID	VARCHAR(30),
PASS	VARCHAR(30),
BIRTH	int(4),
GENDER	VARCHAR(30),
JOB	VARCHAR(30),
ADDRESS	VARCHAR(600),
REGDATE		DATE,
CONSTRAINT MEMBER_PK PRIMARY KEY (ID)
)

INSERT INTO MEMBER VALUES('홍길동', 'HONG', '1234', 1989, '남자', '학생', '서울시 종로구', now());


CREATE TABLE POST(
TITLE VARCHAR(20),
LORE VARCHAR(200),
ID VARCHAR(30),
FILENAME VARCHAR(128),
CREATEDATE DATE,
CONSTRAINT POST_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);
